version: '3.7'
services:
  mysql:
    image: mysql:8.0
    restart: always
    # Uncomment the next two lines to connect to your your database from outside the Docker environment, e.g. using a database GUI like Workbench
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: prisma